CREATE TABLE ENTRY_PATCH_FILES
(
    id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    entry_id  BIGINT       NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    FOREIGN KEY (entry_id) REFERENCES ENTRIES (id) ON DELETE CASCADE
);
